### ISSUE TITLE
Visual distinction for binary output

### ISSUE THREAD

**Issue by nekohayo** [vmkspv/netsleuth#4]
Hi! You might want to consider making the binary output text monospaced to make it ealier to spot where the network vs host separation is, visually speaking.

**Comment by vmkspv** [comment]
Okay, here they are. If I try to fit the binary values into a single line like in the first variant — they don't fit. In the second variant, the monospaced values draw more attention than the regular ones.

I like the third option the most because the font remains consistent, and the binary values are displayed on a new line.

<img src="https://github.com/user-attachments/assets/aa5653b5-be2f-4a15-a0c2-07663db0cfee" width="456" title="Concepts"/>

**Comment by vmkspv** [comment]
Okay, here they are. If I try to fit the binary values into a single line like in the first variant — they don't fit. In the second variant, the monospaced values draw more attention than the regular ones.

I like the third variant the most because the font remains consistent, and the binary values are displayed on a new line.

<img src="https://github.com/user-attachments/assets/ceb03480-b7cb-485d-a076-8de7447df3a7" width="456" title="Concepts"/>

**Comment by s3phy** [comment]
Hi! I was discussing this with nekohayo yesterday and he was quick to open this ticket :)

Having the binary on a new line does give more clarity yes, but I have to say that I prefer proposition #2.

The whole reason is to make it easy to see where the netmask "boundary" is in binary. With a /24 like in your example, it's easy, it's between the third and fourth byte, on the dot in decimal, but with a netmask that is not a multiple of 8 (/21, /22, /27, /28 for example) it's not that obvious anymore, with the font not making the bits "line up" on screen between address and netmask.

With a monospaced font it's kind of obvious whatever the mask is.

Others way I could think of would be to add a space where the boundary is (I think that's what ipcalc does in command line), or maybe a different color for net/host ? (but then you'll probably have to take into account accessibility, desktop theme colors, etc.)

**Comment by vmkspv** [comment]
@s3phy, got the idea! I tried to implement the spacing separation, but creating that logic in the code turned out to be quite challenging, and it might break calculations elsewhere…

<img src="https://github.com/user-attachments/assets/7f831d2c-31a5-45ca-ae6b-7c2272bc39d4" width="746" title="Concepts"/>

I think it makes sense to stick with a monospaced font without any indentation. In fact, it might be worth considering making the entire output monospaced.

**Comment by vmkspv** [comment]
Finally, I came up with these two variants:

<img src="https://github.com/user-attachments/assets/54109265-423c-4977-bccc-189af5c97dcd" width="746" title="Concepts"/>

**Comment by s3phy** [comment]
I like both of these :) They show everything clearly.

**Comment by vmkspv** [comment]
Done in commit 5a7345b0fdd728a8bdf368797988ec70a744da87. The output is also optimal for the mobile layout.

<img src="https://github.com/user-attachments/assets/92fb04bc-1e4b-4887-883b-4c680caafc67" width="286" title="PostmarketOS"/>
